### ISSUE TITLE
Some optional blocks in `auth0_connection` behave differently from each other

### ISSUE THREAD

**Issue by ad8lmondy** [auth0/terraform-provider-auth0#308]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hello, and thanks again for the provider!

I'm trying to pass config values into an `auth0_connection`, so a lot of the variables are optional. Hopefully this gets the idea across:

```terraform
resource "auth0_connection" "auth0" {
  for_each = {
    for x in local.databases : x.name => x
  }

  name     = each.value.name
  strategy = "auth0"

  enabled_clients = []

  options {
    password_policy                = try(each.value.options.password_policy, null)
    brute_force_protection         = try(each.value.options.brute_force_protection, null)
    enabled_database_customization = try(each.value.options.enabled_database_customization, null)
    import_mode                    = try(each.value.options.import_mode, null)
    requires_username              = try(each.value.options.requires_username, null)
    disable_signup                 = try(each.value.options.disable_signup, null)
    configuration                  = try(each.value.options.configuration, null)
    set_user_root_attributes       = try(each.value.options.set_user_root_attributes, null)

    mfa {
      active                 = try(each.value.options.mfa.active, null)
      return_enroll_settings = try(each.value.options.mfa.return_enroll_settings, null)
    }

    password_history {
      enable = try(each.value.options.password_history.enable, null)
      size   = try(each.value.options.password_history.size, null)
    }
  }
}
```
You can see above that almost all variables are either taken from config, or filled with `null`, to indicate that we'll just use whatever the provider sets as the default.

The issue comes in with the blocks within the `options` block. Some of them, like the `mfa` block, work just fine with the above code; while the rest of them, including the `password_history` one, won't work with this setup. On `terraform apply`, it throws this error:
```
╷
│ Error: 400 Bad Request: Payload validation error: 'Expected type boolean but found type null' on property options.password_history.enable.
│ 
│   with auth0_connection.auth0["OEM-DB"],
│   on databases_auth0.tf line 1, in resource "auth0_connection" "auth0":
│    1: resource "auth0_connection" "auth0" {
│ 
╵
```

I go into more detail in the reproduction section, but this seems to be because the `password_history` block is being sent as an empty `{}` map, which fails the payload validation.

### Expectation

My expectation is that I should be able to pass any of the objects below to my `auth0_connection` code, and it to behave "as expected" - that is: if I don't specify a block in the object, it's as if the block was not set in the `auth0_connection`: 
(I know these objects are YAML, but the structure is the same :sweat_smile: ):

```yaml
  - name: no_password_history_no_mfa
    type: auth0
    options:
      brute_force_protection: true
      enabled_database_customization: false
      requires_username: true
      password_policy: "excellent"
      password_no_personal_info: true
  - name: no_mfa
    type: auth0
    options:
      brute_force_protection: true
      enabled_database_customization: false
      requires_username: true
      password_policy: "excellent"
      password_history:
        enable: true
        size: 3
      password_no_personal_info: true
  - name: no_password_history
    type: auth0
    options:
      brute_force_protection: true
      enabled_database_customization: false
      requires_username: true
      password_policy: "excellent"
      mfa:
        active: true
      password_no_personal_info: true
  - name: with_password_history_with_mfa
    type: auth0
    options:
      brute_force_protection: true
      enabled_database_customization: false
      requires_username: true
      password_policy: "excellent"
      password_history:
        enable: true
        size: 3
      mfa:
        active: true
      password_no_personal_info: true
```

At the moment, only `no_mfa` and `with_password_history_with_mfa` will work. The reproduction section (hopefully) explains why.

### Reproduction

Commenting out both the `mfa` and `password_history` blocks in my `auth0_connection`, and creating a brand new DB with this object:
```yaml
  - name: OEM-DB
    type: auth0
    options:
      brute_force_protection: true
      enabled_database_customization: false
      requires_username: true
      password_policy: "excellent"
      password_no_personal_info: true
```
gives
```
  # auth0_connection.auth0["OEM-DB"] will be created
  + resource "auth0_connection" "auth0" {
      + enabled_clients      = (known after apply)
      + id                   = (known after apply)
      + is_domain_connection = (known after apply)
      + name                 = "OEM-DB"
      + realms               = (known after apply)
      + strategy             = "auth0"
      + strategy_version     = (known after apply)

      + options {
          + allowed_audiences              = (known after apply)
          + brute_force_protection         = true
          + domain_aliases                 = (known after apply)
          + enabled_database_customization = false
          + ips                            = (known after apply)
          + non_persistent_attrs           = (known after apply)
          + password_policy                = "excellent"
          + requires_username              = true
          + scopes                         = (known after apply)
          + set_user_root_attributes       = (known after apply)
          + strategy_version               = (known after apply)

          + mfa {
              + active                 = (known after apply)
              + return_enroll_settings = (known after apply)
            }

          + password_complexity_options {
              + min_length = (known after apply)
            }

          + password_dictionary {
              + dictionary = (known after apply)
              + enable     = (known after apply)
            }

          + password_history {
              + enable = (known after apply)
              + size   = (known after apply)
            }

          + password_no_personal_info {
              + enable = (known after apply)
            }
        }
    }
```
and it is applied successfully

Making a single change: add the `mfa` block back into the `auth0_connection`:
```terraform
    mfa {
      active                 = try(each.value.options.mfa.active, null)
      return_enroll_settings = try(each.value.options.mfa.return_enroll_settings, null)
    }
```
the plan looks like:
```
  # auth0_connection.auth0["OEM-DB"] will be updated in-place
  ~ resource "auth0_connection" "auth0" {
        id                   = "con_XYZ"
        name                 = "OEM-DB"
        # (5 unchanged attributes hidden)

      ~ options {
            # (27 unchanged attributes hidden)

          ~ mfa {
              - active                 = true -> null
              - return_enroll_settings = true -> null
            }
        }
    }
```
applying that also works fine.

Now, deleting the whole connection and this same process again, but instead of the `mfa` block, I'll add in the `password_history` block:
```
  # auth0_connection.auth0["OEM-DB"] will be updated in-place
  ~ resource "auth0_connection" "auth0" {
        id                   = "con_DEF"
        name                 = "OEM-DB"
        # (5 unchanged attributes hidden)

      ~ options {
            # (27 unchanged attributes hidden)

          + password_history {}

            # (1 unchanged block hidden)
        }
    }
```
but when I apply it, I get the error:
```
auth0_connection.auth0["OEM-DB"]: Modifying... [id=con_DEF]
╷
│ Error: 400 Bad Request: Payload validation error: 'Expected type boolean but found type null' on property options.password_history.enable.
│ 
│   with auth0_connection.auth0["OEM-DB"],
│   on databases_auth0.tf line 1, in resource "auth0_connection" "auth0":
│    1: resource "auth0_connection" "auth0" {
│ 
╵
```

I think the key is this difference:
```
          ~ mfa {
              - active                 = true -> null
              - return_enroll_settings = true -> null
            }
```
vs
```
          + password_history {}
```
the `mfa` block already exists on a brand new connection, whereas the `password_history` is a new thing - but since it contains 'nothing', the payload is wrong.

The work around I have at the moment is:
```terraform
    dynamic "password_history" {
       for_each = contains(keys(each.value.options), "password_history") ? [null] : []      
       content {
        enable = each.value.options.password_history.enable
        size   = each.value.options.password_history.size
      }
    }
```
which is relatively compact, but quite ugly :sweat_smile:, and it seems that the `mfa` block is the only that doesn't need it.

### Auth0 Terraform Provider version

v0.35.0

### Terraform version

Terraform v1.2.7
